### ISSUE TITLE
Supported versions are not declared in troves

### ISSUE THREAD

**Issue by ztane** [ahupp/python-magic#101]
[Python 3 Wall of Superpowers](http://python3wos.appspot.com/) lists the package as **red**, aka not supporting Python 3. Please add trove classifiers for all supported  Python major versions

**Comment by georgehank** [comment]
It runs under 3.5, but... 3.5 raises FileNotFoundError while this raises IOError in from_file (that's all I've used so far).

Which is an alias of OSError since 3.3, so it actually raises an OSError.  But that is incomplete, since errno isn't set (to the proper errno.ENOENT).  It's incomplete in 2.x also, of course, since IOError is, in this case, supposed to have an ENOENT errno.

It should raise the usual exception based on version: IOError (with errno set to ENOENT by passing it as a second argument to the constructor) for all versions up to 3.2.  3.3 and later should get a FileNotFoundError.

**Comment by ahupp** [comment]
This should be fixed in 0.4.11, including @georgehank's report.  Thanks for your patience.
