### ISSUE TITLE
Document versioning scheme

### ISSUE THREAD

**Issue by remcohaszing** [ahupp/python-magic#112]
I often assume packages use [semver](http://semver.org) when specifying requirements.

I had a project that depends `python-magic`. So I specified this as:

```
python-magic ~= 0.4.11
```

However, `0.4.12` turned out to be a breaking change due to b166698.

Do you follow a specific versioning scheme? I think it would be nice if this is documented.

**Comment by alexkiro** [comment]
Agreed. I want to upgrade to the latest version of this project now. But I don't know what changed so I'm not sure if I can safely upgrade or not. 

Is it possible to have a changelog file :)

**Comment by ahupp** [comment]
This was a big error on my part, I apolgize.  I did not realize the change (IIRC it was return returning str instead of bytes in python3 in some cases) was going to be backwards incompatible and didn't appropriately bump the version.  By the time I realized the issue it seemed less harmful to just continue forward.  I've documented the policy I aspire to here: https://github.com/ahupp/python-magic/blob/master/README.md, and will do my best to stick to it.
