### ISSUE TITLE
Test failures but still promoted to 0.4.15

### ISSUE THREAD

**Issue by robputt796** [ahupp/python-magic#155]
Hi,

A release was tagged and published to PyPi yet the tests in Travis failed, https://travis-ci.org/ahupp/python-magic/jobs/311149225, how do we know this is a sane build that works?

The failures seem to be Travis related e.g. bad Travis node rather than related to the code, however it would be nice to see some green ticks prior to release, can you force the tests to rerun?

Best Regards,

Rob

**Comment by ahupp** [comment]
Sorry about that.   I run the tests locally before submitting rather than relying on travis, though I really should look at travis too.  What happened is that i'd left 'dist: xenial' in the travis config, which didn't do anything b/c they didn't support xenial.  Now they started supporting it, which means it no longer supports some python versions we test against and the build broke.  I've removed those python versions from the travis config and it's clean again.
