### ISSUE TITLE
pip install on Linux without libmagic

### ISSUE THREAD

**Issue by StefanUPB** [ahupp/python-magic#161]
I'd like to use `python-magic` in my python program. Listing `python-magic` in the requirements of `setup.py` installs the Python package but it only works after also installing `libmagic` on Linux.

For Windows, `pip install python-magic-bin` solves the problem. Is there any similar solution for Linux? I.e., I want to install all dependencies with `python setup.py install`.

**Comment by ahupp** [comment]
Every distribution should provide an appropriate package for libmagic, we can't know ahead of time what will work in your particular environment.  The windows -bin package works because you can use the same binaries on every windows machine.    Using your distribution's package is the right way of handling this.

What are you trying to do?

**Comment by StefanUPB** [comment]
I just want to create a python package, using MIME type detection, that can easily be installed with `setup.py`. Any additional dependencies are somewhat of a hassle in my situation.
