### ISSUE TITLE
No wrapper for magic_setparam()

### ISSUE THREAD

**Issue by seirl** [ahupp/python-magic#163]
Sometimes we need to change the parameters of magic, like MAGIC_PARAM_NAME_MAX. There should be a way to call magic_setparam() from the library.

**Comment by ahupp** [comment]
I'd accept a pull request for that feature.

**Comment by seirl** [comment]
Thanks. Could you let the issue open? Generally, issues aren't meant as a way to ask people to work on something, but rather as a way to track what's left to do, so even if you don't want to work on it I think it makes sense for it to remain open in case someone (maybe I) offers to work on it.

**Comment by ahupp** [comment]
Sure.

**Comment by ahupp** [comment]
@cbiedl that looks good to me.  Would you be able to write a test for this as well?

**Comment by cbiedl** [comment]
Okay, here is an attempt for this: The test uses the parameter to limit the size of the file to check. If set to very small values, detection will change.

Otherwise the testing might be a bit too much in detail, but this way both getparam and setparam are tested, and the default value as well. Feel free to trim.

About the API, I'm not sure whether the c_int conversion using .value should rather happen in the library than putting the burden on the caller as it is right now. I'm not that much into Python style yet to decide.

FWIW, the related file invocation is

    file --mime --parameter bytes=1 test/testdata/keep-going.jpg

Note: This test requires at least libmagic 5.26 (released April 2016)

**Comment by cbiedl** [comment]
Web frontends hate me, something ate the attachment. I'll create to create a pull request, what could possibly?

**Comment by ahupp** [comment]
This is released, thanks!
