### ISSUE TITLE
testing with test.py at present works only from parent directory -- suggested patch

### ISSUE THREAD

**Issue by Corin-EU** [ahupp/python-magic#169]
The python test script test.py which is invoked from run.sh can only be successfully run at present if the current directory is the parent directory of test due to the use of relative paths and even hardcoded string paths in test.py.  Furthermore the test of byte representations of file names is only done in Python 3 because the "b" operator is ignored in Python 2 (according to what I have read after much web searching).

Hopefully my replacement of filename.encode as recommended by "agf" at https://stackoverflow.com/questions/7585435/best-way-to-convert-string-to-bytes-in-python-3 provides the necessary equivalent.

I therefore suggest the following changes to test.py which result in the script being executed correctly regardless of the current directory eg even from the test directory its-self in which some people (myself included) first try to run the run.sh script rather than its parent directory.

patch to test/test.py to allow it to be executed independent of current directory:
[test.py.patch.txt](https://github.com/ahupp/python-magic/files/2087322/test.py.patch.txt)

Patch is against current "latest" python-magic revision 3ca9548

**Comment by ahupp** [comment]
Hi Corin,
The `b"..."` syntax is for backwards compatibility in 2.7, but is a no-op in that version.  In either case it produces the same result as "...".encode(..) for these strings in both 2.7 and 3.x.

Thank you for the patches!  I'll go ahead and apply the path changes, but in the future it would make things much easier if you submitted them as pull requests rather than uploading the patch file.

**Comment by ahupp** [comment]
I've applied your patch as 41afcd5, thanks!
