### ISSUE TITLE
magic.MagicException: name use count (30) exceeded

### ISSUE THREAD

**Issue by BookGin** [ahupp/python-magic#190]
```python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> magic.from_buffer(open('python-3.7.2-python-magic-0.4.15.jpg','rb').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 148, in from_buffer
    return m.from_buffer(buffer)
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 82, in from_buffer
    return self._handle509Bug(e)                                                                                       
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 101, in _handle509Bug
    raise e
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 80, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 255, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
  File "/home/bookgin/Desktop/foo/bar/algo/lib/python3.7/site-packages/magic.py", line 188, in errorcheck_null
    raise MagicException(err)
magic.MagicException: b'JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2019 (Windows), datetime=2019:03:06 11:18:46] name use count (30) exceeded'
```

And [here](https://github.com/BookGin/files/blob/master/python-3.7.2-python-magic-0.4.15.jpg) is the file.

Version:
- python: `3.7.2`
- magic: `python-magic==0.4.15`

**Comment by ahupp** [comment]
This error comes from the underlying libmagic library.  I believe you can contact them here: https://mailman.astron.com/mailman/listinfo/file

The mailing list was down for a while and now seems to have moved but I believe this is the up-to-date contact.

**Comment by zoulasc** [comment]
>>> import magic
>>> magic.detect_from_content(open('python-3.7.2-python-magic-0.4.15.jpg','rb').read())
FileMagic(mime_type='image/jpeg', encoding='binary', name=None)

libmagic comes with its own file-magic package that does not suffer from this...

**Comment by ahupp** [comment]
It looks like libmagic is flagging an error (returned by magic_error()), but file-magic doesn't do any error checking.  python-magic checks for errors after each call and raises an exception if one was flagged.

In this case it seems like the error is spurious, but I'm hesitant to just disable that behavior because the expectation in python is that errors are automatically surfaced.

I'm not sure what the best solution is; this is a bug in libmagic but I appreciate this is a pain for your product.  Maybe add a "disable error checking" flag, while also reporting the bug upstream?

**Comment by BookGin** [comment]
When using `from_file()` it does not raise the error,
```python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> magic.from_file('./python-3.7.2-python-magic-0.4.15.jpg')
'JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2019 (Windows), datetime=2019:03:06 11:18:46]'
```

I would expect the behaviors of `from_file()` and `from_buffer()` are the same. Either raise an error or not.

By the way, I reported the bug to the [mailing list](https://mailman.astron.com/mailman/listinfo/file) two weeks ago, but it still awaits moderator's approval. I think the mailing list is not active.

**Comment by zoulasc** [comment]
I don't know what happened to your message, I don't see it in the queue. You can subscribe to the list and then you don't need moderator's approval. 

The file_magic package is a thin wrapper around the library, and you need to do your own error checks... 

The behaviors of the file and data methods are different because the file method does not read the whole file (so it does not get to parse all the parameters). This is for efficiency. I am thinking of providing a way to change the limit or raise the default though. You can see this if you raise the name depth parameter and allow it to complete.

So the file method returns:

JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2019 (Windows), datetime=2019:03:06 11:18:46]

And the buffer method returns:

JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2019 (Windows), datetime=2019:03:06 11:18:46], baseline, precision 8, 1850x450, components 3

Also perhaps the name recursion depth of 30 is probably too short :-)

**Comment by ddnomad** [comment]
Just encountered the same issue. Anybody was able to fix it using `from_buffer`?

**Comment by MysticKevin** [comment]
Just encountered the same issue, using `from_buffer()`

  File "/var/task/ljlkhl/intaque/__init__.py", line 1461, in getFiletypeInformationFromContent
    details = magic.from_buffer(recordBuffer)
  File "/var/task/magic.py", line 148, in from_buffer
    return m.from_buffer(buffer)
  File "/var/task/magic.py", line 82, in from_buffer
    return self._handle509Bug(e)
  File "/var/task/magic.py", line 101, in _handle509Bug
    raise e
  File "/var/task/magic.py", line 80, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
  File "/var/task/magic.py", line 255, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
  File "/var/task/magic.py", line 188, in errorcheck_null
    raise MagicException(err)
magic.MagicException: b'JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=15, height=5760, bps=0, manufacturer=HUAWEI, model=PCT-L29, orientation=[*0*], xresolution=210, yresolution=218, resolutionunit=2, software=PCT-L29 9.1.0.237(C432E1R2P1), datetime=2019:10:25 20:43:15, GPS-Data, width=4304] name use count (30) exceeded'

**Comment by ahupp** [comment]
@zoulasc pointed to the solution, there's a parameter that controls this.  I've bumped up the value to 64 in https://github.com/ahupp/python-magic/commit/8852eafff7c8d0b386a6b648fff5b51602014f2b, and this at least prevents the error for @BookGin 's example.  

@ddnomad / @BookGin : see the commit above, you can do the setparam call directly to fix this locally.

**Comment by michaelweiser** [comment]
Sorry to necro, but I just ran into this issue as well and wanted to give some feedback. With my sample the issue occurs with both `from_buffer()` and `from_file()`. Releases 0.4.17 and 0.4.18 fix both cases for me. Thanks!

**Comment by jakeogh** [comment]
I hit this with the updated limit (64):
https://www.vandenberg.spaceforce.mil/portals/18/documents/SLD30/SLD30-Mission.jpg

```
Python 3.11.5 (main, Aug 25 2023, 00:06:00) [GCC 12.2.1 20230304] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> magic.from_buffer(open('SLD30-Mission.jpg','rb').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 192, in from_buffer
    return m.from_buffer(buffer)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 108, in from_buffer
    return self._handle509Bug(e)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 135, in _handle509Bug
    raise e
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 106, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 307, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/magic/__init__.py", line 217, in errorcheck_null
    raise MagicException(err)
magic.MagicException: b'JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2018 (Windows), datetime=2021:05:20 10:52:08] name use count (64) exceeded'
```

**Comment by ahupp** [comment]
@jakeogh what does `magic.version()` return?  From comments earlier it sounds like this is a bug in libmagic that was fixed a while ago.

**Comment by jakeogh** [comment]
@ahupp 
magic.version(): 545
