### ISSUE TITLE
magic.py file collision

### ISSUE THREAD

**Issue by nicfit** [ahupp/python-magic#21]
Hi,

I use python-magic in eyeD3 and am quite happy with it, thanks!

On gentoo, at least, there is a package called sys-apps/file that provides libmagic.so and lays down a magic.py in site-packages. This collides with python-magic's file.. Which was first? I'm thinking of patching python-magic at install time to have a different module name. Or.. is python-magic going to replace what is in the 'file' pkg someday?

**Comment by sebix** [comment]
Are there any updates to this problem? Have there been solutions for some distributions?

We are facing the same problem in openSUSE.

**Comment by ahupp** [comment]
I have an experimental branch that merges the interfaces of python-magic (this library) and the one shipped in libmagic.  https://github.com/ahupp/python-magic/tree/libmagic-compat

Want to take a look?

**Comment by cazino** [comment]
Hi,

Do you have plans to merge the libmagic-compat in master ? It would be very helpful for software maintainers who want to have portability between a debian/stable and a pypi installation for exemple.      
Of course I would be glad to provide some help if you need any.

Regards.

**Comment by sim0nx** [comment]
Hi,

Any possibility you could merge that branch into master and bump the version please?

**Comment by akien-mga** [comment]
Is there any update on this?

I'm also running into issues due to this conflict between [`file`](http://www.darwinsys.com/file/)'s Python bindings (pip name `file-magic`) and this package (pip name `python-magic`) which both provide conflicting `magic.py`.

I'm a packager for the Mageia Linux distro and [Lutris](https://github.com/lutris/lutris) recently started using this package (`python-magic`), and packaging it was a headache due to the conflict with `file`. Now it generates a situation where software that uses `file-magic` e.g. `rpmlint`) can't be used together with software that uses `python-magic`.
Downstream bug report: https://bugs.mageia.org/show_bug.cgi?id=27619

Currently I might hack things around by renaming `python-magic`'s module to `python-magic.py` and patching Lutris code accordingly, since it's my only packaged application using this module... but it's not a good long term solution.

**Comment by jasontibbitts** [comment]
Just a note that this has now come up in Fedora as well: https://bugzilla.redhat.com/show_bug.cgi?id=1899279

**Comment by SchoolGuy** [comment]
@ahupp So all distros which want to package your code now have this problem due to the naming conflict. Can we somehow help you?

**Comment by ahupp** [comment]
I forgot to update this issue, but it should be fixed with the compatibility layer shipped on 0.4.20.
