### ISSUE TITLE
Win64 DLL location

### ISSUE THREAD

**Issue by steveshaddick** [ahupp/python-magic#34]
Please note that on Windows 7 64bit the dependent DLLs need to be placed in C:\Windows\SysWOW64 (not C:\Windows\System32).

**Comment by oba2cat3** [comment]
you can also use this build:
[pidydx](https://github.com/pidydx/libmagicwin64)

**Comment by patriotpie** [comment]
I'm using Win10 x64 with updates. I had an error using the DLLs linked by @oba2cat3. However I used @iljau's sources and got this working. [Dependency Walker](http://www.dependencywalker.com/) gave `msys-2.0.dll` and `msys-z.dll` as dependencies of `file.exe` for package version `file-5.29-1`.

**Win10 x64 steps**
Download from [the x86_64 MSYS build repository](https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/):
* `msys-file` package.
* `msys2-runtime` package. Drop `usr/bin/msys-2.0.dll` inside the `usr/bin` folder of `msys-file` package.
* `zlib` package. Drop `usr/bin/msys-z.dll` inside the `usr/bin` folder of `msys-file` package.

To get `import magic` working correctly make sure that the three DLLs are somewhere on your PATH. I also had to add the string value `'msys-magic-1.dll'` to [the list stored in `windows_dlls` of `magic.py`](https://github.com/ahupp/python-magic/blob/271ae7a1483d2fcf336257c89c0c750474c3281f/magic.py#L157) so that the module init searched for the MSYS version. Alternatively you can just rename `msys-magic-1.dll` -> `magic1.dll` if you don't want to change the contents of package files.

**Comment by ahupp** [comment]
Merging into https://github.com/ahupp/python-magic/issues/293
