### ISSUE TITLE
failures to catch errors in checks with latest libmagic compiled with mingw on windows

### ISSUE THREAD

**Issue by pombreda** [ahupp/python-magic#77]
I am having cases where the returned type is actually a libmagic error message and no exception was raised by python-magic.  This happens when libmagic returns -1 which could be some artifact of the mingw/windows build.
Since `_magic_file.errcheck = errorcheck_null`, and errorcheck_null does not check for anything but nulls, things go south from there.
There are plenty of cases where this can happen.

**Comment by ahupp** [comment]
magic_file is declared to return "const char*", so it could not return -1.  The docs say:

"The magic_buffer(), magic_getpath(), and magic_file(), functions return a string on success and NULL on failure."

If you're getting an error message instead of an exception this sounds like a libmagic bug.  I'd suggest debugging into and/or readling libmagic to track down where this is coming from.
